# Oliver-200 · параметры сборки. Подпись: OLIVER-200 · см. SIGNATURES.txt
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

kotlin.code.style=official

# Android (используются только когда подключён модуль :app)
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
